### ISSUE TITLE
May it a littler clearer that the type samples are just that

### ISSUE THREAD

**Issue by bruce-usab** [Myndex/SAPC#1]
I do not think that

> Minimum Size Type Examples for Testing Various Levels

is very clear.  My suggestions:
1. add a horizontal rule above the heading
2. change the heading to "Type Samples (that use your selected colors)"

**Comment by Myndex** [comment]
> I do not think that
> 
> > Minimum Size Type Examples for Testing Various Levels
> 
> is very clear. My suggestions:
> 
> 1. add a horizontal rule above the heading
> 2. change the heading to "Type Samples (that use your selected colors)"

Hi @bruce-usab 

Okay, good idea. I'll update on the next pass.

A

**Comment by Myndex** [comment]
More enhancements to the page, for this, there is now a contrast indicator that changed from green to yellow , orange athen red depending on how far out the contrast is for the given line/weight of type.

Also added the new lookup table to the page, I hope this all helps to make things clear — feedback always welcome as you know...

Thank you!
Andy
