### ISSUE TITLE
Feature request:  provide URL for chosen colors

### ISSUE THREAD

**Issue by bruce-usab** [Myndex/SAPC#2]
I would like to be able to give someone a URL to SAPC that starts with my chosen colors.

For example the WebAIM Contrast Checker has a "permalink" feature, so I can start with red on white:
http://webaim.org/resources/contrastchecker/?fcolor=FF0000&bcolor=FFFFFF

**Comment by Myndex** [comment]
> I would like to be able to give someone a URL to SAPC that starts with my chosen colors.

Hi @bruce-usab  That's a good idea, I'll add it to the updates queue. Shouldn't be too hard.

A

**Comment by Myndex** [comment]
Done, URLs with the color, and a number of other enhancements.

For giggles, here's the **WorstColorPairEver**™

https://www.myndex.com/SAPC/?BG=ff0000&txt=009d00

**Comment by bruce-usab** [comment]
That is impressive!  I had assumes a zero was only possible with two identical colors!

**Comment by Myndex** [comment]
> That is impressive! I had assumes a zero was only possible with two identical colors!

Hey @bruce-usab   Well, might not be a true zero... the math clamps all contrasts under 15% to zero, as that avoids a significant complication in the math, which I have attempted to make as simple as possible!
